name: Test setup.sh

on:
  workflow_call:
  push:
    paths:
    - "setup.sh"
    - ".github/workflows/setup-sh.yml"
  pull_request:
    paths:
    - "setup.sh"
    - ".github/workflows/setup-sh.yml"

jobs:
  build_windows:
    strategy:
      matrix:
        os:
        - windows-2022
        python:
        - "3.8"
        - "3.9"
        - "3.10"
      fail-fast: false
    name: Run setup on ${{ matrix.os }} with python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Run setup.ps1
      if: matrix.os == 'windows-2022'
      run: .\setup.ps1
    - name: Test angr import
      run: python -c "import angr; print('angr imports!')"

  build_macos:
    strategy:
      matrix:
        os:
        - macos-12
        python:
        - "3.8"
        - "3.9"
        - "3.10"
      fail-fast: false
    name: Run setup on ${{ matrix.os }} with python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Upgrade bash
      if: matrix.os == 'macos-12'
      run: brew install bash
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Run setup.sh
      run: ./setup.sh -i -u -v
    - name: Test angr import
      run: python -c "import angr; print('angr imports!')"

  build_linux:
    strategy:
      matrix:
        container:
        - ubuntu:focal
        - ubuntu:jammy
        - archlinux:latest
        - fedora:36
        - almalinux:9
        # OpenSUSE is disabled because they don't include tar
        # - opensuse/leap:15
        # - opensuse/tumbleweed:latest
      fail-fast: false
    name: Run setup on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v3
    - name: Install python3
      run: |
        # Don't try to cover everything, just what's in CI
        source /etc/os-release
        [ "$ID" -eq "ubuntu" ] && apt update; apt install -y python3-venv
        [ "$ID" -eq "arch" ] && pacman -Syu python
        [ "$ID" -eq "fedora" ] && dnf install python3
        [ "$ID" -eq "almalinux" ] && yum install python3
        python3 -m venv venv
    - name: Run setup.sh
      run: source venv/bin/activate && ./setup.sh -i -u
    - name: Test angr import
      run: python -c "import angr; print('angr imports!')"

    - name: Test angr management import
      run: python -c "import angrmanagement; print('angr management imports!')"
